2013/06/08 18:07:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('test')
#1 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/YII/demos/blog/index.php/test
---
2013/06/08 18:08:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "aboutd" was not found.' in D:\Website\YII\framework\web\actions\CViewAction.php:112
Stack trace:
#0 D:\Website\YII\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('aboutd')
#1 D:\Website\YII\framework\web\actions\CAction.php(76): CViewAction->run()
#2 D:\Website\YII\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('page')
#6 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#9 {main}
REQUEST_URI=/YII/demos/blog/index.php/site/page?view=aboutd
---
2013/06/30 02:56:27 [error] [php] Undefined variable: data (D:\Website\YII\demos\blog\protected\views\post\index.php:12)
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(869): PostController->renderFile()
#1 D:\Website\YII\framework\web\CController.php(782): PostController->renderPartial()
#2 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): PostController->render()
#3 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#4 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(133): PostController->runAction()
#6 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): PostController->filterAccessControl()
#9 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#11 D:\Website\YII\framework\web\CController.php(265): PostController->runActionWithFilters()
#12 D:\Website\YII\framework\web\CWebApplication.php(282): PostController->run()
#13 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 D:\Website\YII\demos\blog\index.php(11): CWebApplication->run()
REQUEST_URI=/YII/demos/blog/index.php/post/index
2013/06/30 02:57:05 [error] [php] Undefined variable: data (D:\Website\YII\demos\blog\protected\views\post\index.php:12)
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(869): PostController->renderFile()
#1 D:\Website\YII\framework\web\CController.php(782): PostController->renderPartial()
#2 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): PostController->render()
#3 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#4 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(133): PostController->runAction()
#6 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): PostController->filterAccessControl()
#9 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#11 D:\Website\YII\framework\web\CController.php(265): PostController->runActionWithFilters()
#12 D:\Website\YII\framework\web\CWebApplication.php(282): PostController->run()
#13 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 D:\Website\YII\demos\blog\index.php(11): CWebApplication->run()
REQUEST_URI=/YII/demos/blog/index.php/post/index
2013/06/30 02:57:06 [error] [php] Undefined variable: data (D:\Website\YII\demos\blog\protected\views\post\index.php:12)
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(869): PostController->renderFile()
#1 D:\Website\YII\framework\web\CController.php(782): PostController->renderPartial()
#2 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): PostController->render()
#3 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#4 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(133): PostController->runAction()
#6 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): PostController->filterAccessControl()
#9 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#11 D:\Website\YII\framework\web\CController.php(265): PostController->runActionWithFilters()
#12 D:\Website\YII\framework\web\CWebApplication.php(282): PostController->run()
#13 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 D:\Website\YII\demos\blog\index.php(11): CWebApplication->run()
REQUEST_URI=/YII/demos/blog/index.php/post/index
2013/06/30 02:59:44 [error] [exception.CException] exception 'CException' with message 'PostController and its behaviors do not have a method or closure named "loadModel".' in D:\Website\YII\framework\base\CComponent.php:265
Stack trace:
#0 D:\Website\YII\demos\blog\protected\controllers\PostController.php(48): CComponent->__call('loadModel', Array)
#1 D:\Website\YII\demos\blog\protected\controllers\PostController.php(48): PostController->loadModel()
#2 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionView()
#3 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#10 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('view')
#12 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/view')
#13 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#15 {main}
REQUEST_URI=/YII/demos/blog/index.php/post/2/A+Test+Post
HTTP_REFERER=http://localhost/YII/demos/blog/index.php/post/index
---
2013/06/30 03:00:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in D:\Website\YII\framework\web\CController.php:483
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(270): CController->missingAction('view')
#1 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('view')
#2 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/view')
#3 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/YII/demos/blog/index.php/post/2/A+Test+Post
HTTP_REFERER=http://localhost/YII/demos/blog/index.php/post/index
---
2013/06/30 03:04:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in D:\Website\YII\demos\blog\protected\controllers\PostController.php:181
Stack trace:
#0 D:\Website\YII\demos\blog\protected\controllers\PostController.php(48): PostController->loadModel()
#1 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionView()
#2 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#4 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#6 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#9 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('view')
#11 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/view')
#12 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#14 {main}
REQUEST_URI=/YII/demos/blog/index.php/post/2/A+Test+Post
HTTP_REFERER=http://localhost/YII/demos/blog/index.php/post/index
---
2013/06/30 03:13:12 [error] [php] include(Post.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\Website\YII\framework\YiiBase.php:421)
Stack trace:
#0 D:\Website\YII\demos\blog\protected\controllers\PostController.php(177): spl_autoload_call()
#1 D:\Website\YII\demos\blog\protected\controllers\PostController.php(48): PostController->loadModel()
#2 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionView()
#3 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\Website\YII\framework\web\filters\CFilterChain.php(133): PostController->runAction()
#5 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\Website\YII\framework\web\CController.php(1145): CAccessControlFilter->filter()
#7 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): PostController->filterAccessControl()
#8 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#9 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#10 D:\Website\YII\framework\web\CController.php(265): PostController->runActionWithFilters()
#11 D:\Website\YII\framework\web\CWebApplication.php(282): PostController->run()
#12 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\Website\YII\demos\blog\index.php(11): CWebApplication->run()
REQUEST_URI=/YII/demos/blog/index.php/post/2/A+Test+Post
2013/06/30 03:18:51 [error] [exception.CException] exception 'CException' with message 'Property "PostController.model" is not defined.' in D:\Website\YII\framework\base\CComponent.php:130
Stack trace:
#0 D:\Website\YII\demos\blog\protected\controllers\PostController.php(172): CComponent->__get('model')
#1 D:\Website\YII\demos\blog\protected\controllers\PostController.php(48): PostController->loadModel()
#2 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionView()
#3 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#10 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('view')
#12 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/view')
#13 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#15 {main}
REQUEST_URI=/YII/demos/blog/index.php/post/2/A+Test+Post
HTTP_REFERER=http://localhost/YII/demos/blog/index.php
---
2013/07/01 05:19:52 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in D:\Website\YII\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\Website\YII\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 D:\Website\YII\demos\blog\protected\models\User.php(20): CActiveRecord::model('User')
#2 D:\Website\YII\demos\blog\protected\components\UserIdentity.php(18): User::model()
#3 D:\Website\YII\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#4 D:\Website\YII\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 D:\Website\YII\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\Website\YII\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 D:\Website\YII\framework\web\widgets\CActiveForm.php(835): CModel->validate(NULL)
#8 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(73): CActiveForm::validate(Object(LoginForm))
#9 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#14 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#16 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/site/login.html
---
2013/07/01 05:19:53 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in D:\Website\YII\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\Website\YII\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 D:\Website\YII\demos\blog\protected\models\User.php(20): CActiveRecord::model('User')
#2 D:\Website\YII\demos\blog\protected\components\UserIdentity.php(18): User::model()
#3 D:\Website\YII\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#4 D:\Website\YII\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 D:\Website\YII\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\Website\YII\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 D:\Website\YII\framework\web\widgets\CActiveForm.php(835): CModel->validate(NULL)
#8 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(73): CActiveForm::validate(Object(LoginForm))
#9 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#14 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#16 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/site/login.html
---
2013/07/01 05:19:53 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in D:\Website\YII\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\Website\YII\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 D:\Website\YII\demos\blog\protected\models\User.php(20): CActiveRecord::model('User')
#2 D:\Website\YII\demos\blog\protected\components\UserIdentity.php(18): User::model()
#3 D:\Website\YII\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#4 D:\Website\YII\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 D:\Website\YII\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\Website\YII\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(82): CModel->validate()
#8 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#13 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/site/login.html
---
2013/07/01 05:20:00 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in D:\Website\YII\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\Website\YII\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 D:\Website\YII\demos\blog\protected\models\User.php(20): CActiveRecord::model('User')
#2 D:\Website\YII\demos\blog\protected\components\UserIdentity.php(18): User::model()
#3 D:\Website\YII\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#4 D:\Website\YII\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 D:\Website\YII\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\Website\YII\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 D:\Website\YII\framework\web\widgets\CActiveForm.php(835): CModel->validate(NULL)
#8 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(73): CActiveForm::validate(Object(LoginForm))
#9 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#14 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#16 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/site/login.html
---
2013/07/01 05:20:03 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in D:\Website\YII\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\Website\YII\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 D:\Website\YII\demos\blog\protected\models\User.php(20): CActiveRecord::model('User')
#2 D:\Website\YII\demos\blog\protected\components\UserIdentity.php(18): User::model()
#3 D:\Website\YII\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#4 D:\Website\YII\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 D:\Website\YII\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\Website\YII\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 D:\Website\YII\framework\web\widgets\CActiveForm.php(835): CModel->validate(NULL)
#8 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(73): CActiveForm::validate(Object(LoginForm))
#9 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#14 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#16 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/site/login.html
---
2013/07/01 05:20:03 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in D:\Website\YII\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\Website\YII\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 D:\Website\YII\demos\blog\protected\models\User.php(20): CActiveRecord::model('User')
#2 D:\Website\YII\demos\blog\protected\components\UserIdentity.php(18): User::model()
#3 D:\Website\YII\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#4 D:\Website\YII\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 D:\Website\YII\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\Website\YII\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(82): CModel->validate()
#8 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#13 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/site/login.html
---
2013/07/01 07:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/07/01 07:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/07/01 07:12:23 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "loginx".' in D:\Website\YII\framework\web\CController.php:878
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(782): CController->renderPartial('loginx', Array, true)
#1 D:\Website\YII\demos\blog\protected\controllers\SiteController.php(86): CController->render('loginx', Array)
#2 D:\Website\YII\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\Website\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('login')
#7 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#8 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/site/login.html
HTTP_REFERER=http://www.blog.dev/
---
2013/07/05 17:10:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/07/07 07:09:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/07/07 07:12:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "home".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#1 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/home.aspx
---
2013/07/07 07:13:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\Website\YII\framework\web\CController.php:483
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(270): CController->missingAction('')
#1 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#3 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/home.aspx
---
2013/07/07 07:13:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\Website\YII\framework\web\CController.php:483
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(270): CController->missingAction('')
#1 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#3 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/home.aspx
---
2013/07/07 07:13:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\Website\YII\framework\web\CController.php:483
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(270): CController->missingAction('')
#1 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#3 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/home.aspx
---
2013/07/07 07:13:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\Website\YII\framework\web\CController.php:483
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(270): CController->missingAction('')
#1 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#3 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/home.aspx
---
2013/07/07 07:13:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\Website\YII\framework\web\CController.php:483
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(270): CController->missingAction('')
#1 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#3 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/home.aspx
---
2013/07/07 07:14:35 [error] [php] Undefined variable: dataProvider (D:\Website\YII\demos\blog\protected\views\home\index.php:6)
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(869): HomeController->renderFile()
#1 D:\Website\YII\framework\web\CController.php(782): HomeController->renderPartial()
#2 D:\Website\YII\demos\blog\protected\controllers\HomeController.php(28): HomeController->render()
#3 D:\Website\YII\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#4 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\Website\YII\framework\web\CController.php(286): HomeController->runAction()
#6 D:\Website\YII\framework\web\CController.php(265): HomeController->runActionWithFilters()
#7 D:\Website\YII\framework\web\CWebApplication.php(282): HomeController->run()
#8 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\Website\YII\demos\blog\index.php(11): CWebApplication->run()
REQUEST_URI=/home.aspx
2013/07/07 07:14:38 [error] [php] Undefined variable: dataProvider (D:\Website\YII\demos\blog\protected\views\home\index.php:6)
Stack trace:
#0 D:\Website\YII\framework\web\CController.php(869): HomeController->renderFile()
#1 D:\Website\YII\framework\web\CController.php(782): HomeController->renderPartial()
#2 D:\Website\YII\demos\blog\protected\controllers\HomeController.php(28): HomeController->render()
#3 D:\Website\YII\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#4 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\Website\YII\framework\web\CController.php(286): HomeController->runAction()
#6 D:\Website\YII\framework\web\CController.php(265): HomeController->runActionWithFilters()
#7 D:\Website\YII\framework\web\CWebApplication.php(282): HomeController->run()
#8 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\Website\YII\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\Website\YII\demos\blog\index.php(11): CWebApplication->run()
REQUEST_URI=/home.aspx
2013/08/16 05:05:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in D:\Website\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/YII/demos/blog/gii
---
2013/10/09 15:07:40 [error] [exception.CException] exception 'CException' with message 'CPhpAuthManager and its behaviors do not have a method or closure named "getAssignmentsByItemName".' in D:\Website\YII\framework\base\CComponent.php:266
Stack trace:
#0 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CComponent->__call('getAssignmentsB...', Array)
#1 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CPhpAuthManager->getAssignmentsByItemName('Admin')
#2 D:\Website\YII\demos\blog\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#3 D:\Website\YII\framework\web\CController.php(1144): AssignmentController->accessRules()
#4 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#10 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/YII/demos/blog/rights
---
2013/10/09 15:09:55 [error] [exception.CException] exception 'CException' with message 'CPhpAuthManager and its behaviors do not have a method or closure named "getAssignmentsByItemName".' in D:\Website\YII\framework\base\CComponent.php:266
Stack trace:
#0 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CComponent->__call('getAssignmentsB...', Array)
#1 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CPhpAuthManager->getAssignmentsByItemName('Admin')
#2 D:\Website\YII\demos\blog\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#3 D:\Website\YII\framework\web\CController.php(1144): AssignmentController->accessRules()
#4 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#10 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/YII/demos/blog/rights
---
2013/10/09 15:09:57 [error] [exception.CException] exception 'CException' with message 'CPhpAuthManager and its behaviors do not have a method or closure named "getAssignmentsByItemName".' in D:\Website\YII\framework\base\CComponent.php:266
Stack trace:
#0 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CComponent->__call('getAssignmentsB...', Array)
#1 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CPhpAuthManager->getAssignmentsByItemName('Admin')
#2 D:\Website\YII\demos\blog\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#3 D:\Website\YII\framework\web\CController.php(1144): AssignmentController->accessRules()
#4 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#10 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/YII/demos/blog/rights
---
2013/10/09 15:10:25 [error] [exception.CException] exception 'CException' with message 'CPhpAuthManager and its behaviors do not have a method or closure named "getAssignmentsByItemName".' in D:\Website\YII\framework\base\CComponent.php:266
Stack trace:
#0 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CComponent->__call('getAssignmentsB...', Array)
#1 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CPhpAuthManager->getAssignmentsByItemName('Admin')
#2 D:\Website\YII\demos\blog\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#3 D:\Website\YII\framework\web\CController.php(1144): AssignmentController->accessRules()
#4 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#10 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/YII/demos/blog/rights
---
2013/10/09 15:10:26 [error] [exception.CException] exception 'CException' with message 'CPhpAuthManager and its behaviors do not have a method or closure named "getAssignmentsByItemName".' in D:\Website\YII\framework\base\CComponent.php:266
Stack trace:
#0 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CComponent->__call('getAssignmentsB...', Array)
#1 D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php(285): CPhpAuthManager->getAssignmentsByItemName('Admin')
#2 D:\Website\YII\demos\blog\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#3 D:\Website\YII\framework\web\CController.php(1144): AssignmentController->accessRules()
#4 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#7 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#10 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/YII/demos/blog/rights
---
2013/10/09 15:13:06 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'There must be at least one superuser!' in D:\Website\YII\demos\blog\protected\modules\rights\components\RAuthorizer.php:305
Stack trace:
#0 D:\Website\YII\demos\blog\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#1 D:\Website\YII\framework\web\CController.php(1144): AssignmentController->accessRules()
#2 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#5 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#8 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/YII/demos/blog/rights
---
2014/03/22 17:11:38 [error] [exception.CDbException] SQLSTATE[HY000] [1049] Unknown database 'db_test'
2014/03/22 17:11:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\Website\YII\framework\db\CDbConnection.php:388
Stack trace:
#0 D:\Website\YII\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\Website\YII\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\Website\YII\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\Website\YII\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\Website\YII\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\Website\YII\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 D:\Website\YII\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 D:\Website\YII\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 D:\Website\YII\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 D:\Website\YII\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 D:\Website\YII\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 D:\Website\YII\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 D:\Website\YII\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 D:\Website\YII\framework\web\CBaseController.php(147): CListView->init()
#14 D:\Website\YII\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 D:\Website\YII\demos\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#16 D:\Website\YII\framework\web\CBaseController.php(126): require('D:\Website\YII\...')
#17 D:\Website\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\Website\YII\...', Array, true)
#18 D:\Website\YII\framework\web\CController.php(869): CBaseController->renderFile('D:\Website\YII\...', Array, true)
#19 D:\Website\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#21 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#22 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#29 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#31 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#32 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#34 {main}
REQUEST_URI=/YII/demos/blog/
HTTP_REFERER=http://localhost/YII/demos/
---
2014/03/22 17:11:42 [error] [exception.CDbException] SQLSTATE[HY000] [1049] Unknown database 'db_test'
2014/03/22 17:11:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\Website\YII\framework\db\CDbConnection.php:388
Stack trace:
#0 D:\Website\YII\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\Website\YII\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\Website\YII\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\Website\YII\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\Website\YII\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\Website\YII\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 D:\Website\YII\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 D:\Website\YII\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 D:\Website\YII\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 D:\Website\YII\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 D:\Website\YII\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 D:\Website\YII\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 D:\Website\YII\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 D:\Website\YII\framework\web\CBaseController.php(147): CListView->init()
#14 D:\Website\YII\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 D:\Website\YII\demos\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#16 D:\Website\YII\framework\web\CBaseController.php(126): require('D:\Website\YII\...')
#17 D:\Website\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\Website\YII\...', Array, true)
#18 D:\Website\YII\framework\web\CController.php(869): CBaseController->renderFile('D:\Website\YII\...', Array, true)
#19 D:\Website\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#21 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#22 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#29 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('index')
#31 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/index')
#32 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#34 {main}
REQUEST_URI=/YII/demos/blog/post/index.html
HTTP_REFERER=http://localhost/YII/demos/blog/site/login.html
---
2014/03/22 17:11:44 [error] [exception.CDbException] SQLSTATE[HY000] [1049] Unknown database 'db_test'
2014/03/22 17:11:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\Website\YII\framework\db\CDbConnection.php:388
Stack trace:
#0 D:\Website\YII\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\Website\YII\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\Website\YII\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\Website\YII\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\Website\YII\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\Website\YII\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 D:\Website\YII\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 D:\Website\YII\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 D:\Website\YII\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 D:\Website\YII\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 D:\Website\YII\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 D:\Website\YII\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 D:\Website\YII\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 D:\Website\YII\framework\web\CBaseController.php(147): CListView->init()
#14 D:\Website\YII\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 D:\Website\YII\demos\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#16 D:\Website\YII\framework\web\CBaseController.php(126): require('D:\Website\YII\...')
#17 D:\Website\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\Website\YII\...', Array, true)
#18 D:\Website\YII\framework\web\CController.php(869): CBaseController->renderFile('D:\Website\YII\...', Array, true)
#19 D:\Website\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#21 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#22 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#29 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#31 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#32 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#34 {main}
REQUEST_URI=/YII/demos/blog/
HTTP_REFERER=http://localhost/YII/demos/
---
2014/07/10 12:14:15 [error] [exception.CDbException] SQLSTATE[HY000] [1049] Unknown database 'db_test'
2014/07/10 12:14:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\Website\YII\framework\db\CDbConnection.php:388
Stack trace:
#0 D:\Website\YII\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\Website\YII\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\Website\YII\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\Website\YII\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\Website\YII\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\Website\YII\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 D:\Website\YII\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 D:\Website\YII\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 D:\Website\YII\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 D:\Website\YII\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 D:\Website\YII\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 D:\Website\YII\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 D:\Website\YII\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 D:\Website\YII\framework\web\CBaseController.php(147): CListView->init()
#14 D:\Website\YII\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 D:\Website\YII\demos\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#16 D:\Website\YII\framework\web\CBaseController.php(126): require('D:\Website\YII\...')
#17 D:\Website\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\Website\YII\...', Array, true)
#18 D:\Website\YII\framework\web\CController.php(869): CBaseController->renderFile('D:\Website\YII\...', Array, true)
#19 D:\Website\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 D:\Website\YII\demos\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#21 D:\Website\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#22 D:\Website\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 D:\Website\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 D:\Website\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 D:\Website\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 D:\Website\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 D:\Website\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 D:\Website\YII\framework\web\CController.php(291): CFilterChain->run()
#29 D:\Website\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 D:\Website\YII\framework\web\CWebApplication.php(282): CController->run('')
#31 D:\Website\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#32 D:\Website\YII\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 D:\Website\YII\demos\blog\index.php(11): CApplication->run()
#34 {main}
REQUEST_URI=/YII/demos/blog/
HTTP_REFERER=http://localhost/YII/demos/
---
2014/07/31 22:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/31 22:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/31 22:11:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:12:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:12:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:13:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:14:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:14:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:14:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:15:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:16:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:16:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "insert".' in D:\Website\YII_ENGINE_1.1.15\web\CController.php:483
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(270): CController->missingAction('insert')
#1 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CController->run('insert')
#2 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('cart/insert')
#3 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/cart/insert
---
2014/07/31 22:16:35 [error] [php] include(Cart.php): failed to open stream: No such file or directory (D:\Website\YII_ENGINE_1.1.15\YiiBase.php:427)
Stack trace:
#0 D:\Website\YIIMOLTINCART\protected\controllers\CartController.php(24): spl_autoload_call()
#1 D:\Website\YII_ENGINE_1.1.15\web\actions\CInlineAction.php(49): CartController->actionInsert()
#2 D:\Website\YII_ENGINE_1.1.15\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\Website\YII_ENGINE_1.1.15\web\CController.php(286): CartController->runAction()
#4 D:\Website\YII_ENGINE_1.1.15\web\CController.php(265): CartController->runActionWithFilters()
#5 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CartController->run()
#6 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#8 D:\Website\YIIMOLTINCART\index.php(11): CWebApplication->run()
REQUEST_URI=/cart/insert
2014/07/31 22:19:07 [error] [php] include(D:\Website\YIIMOLTINCART\protected\vendors\MoltinCart\vendor/autoload.php): failed to open stream: No such file or directory (D:\Website\YIIMOLTINCART\protected\controllers\CartController.php:12)
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController()
#1 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\Website\YIIMOLTINCART\index.php(11): CWebApplication->run()
REQUEST_URI=/cart/insert
2014/07/31 22:20:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/31 22:20:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php:286
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\Website\YIIMOLTINCART\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/31 22:20:36 [error] [php] Argument 2 passed to Moltin\Cart\Cart::__construct() must be an instance of Moltin\Cart\IdentifierInterface, none given, called in D:\Website\YIIMOLTINCART\protected\controllers\CartController.php on line 60 and defined (D:\Website\YIIMOLTINCART\protected\vendors\MoltinCart\src\Moltin\Cart\Cart.php:48)
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\Website\YII_ENGINE_1.1.15\web\CController.php(286): CartController->runAction()
#2 D:\Website\YII_ENGINE_1.1.15\web\CController.php(265): CartController->runActionWithFilters()
#3 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CartController->run()
#4 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\Website\YIIMOLTINCART\index.php(11): CWebApplication->run()
REQUEST_URI=/cart/read
2014/07/31 22:20:41 [error] [php] Argument 2 passed to Moltin\Cart\Cart::__construct() must be an instance of Moltin\Cart\IdentifierInterface, none given, called in D:\Website\YIIMOLTINCART\protected\controllers\CartController.php on line 28 and defined (D:\Website\YIIMOLTINCART\protected\vendors\MoltinCart\src\Moltin\Cart\Cart.php:48)
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\Website\YII_ENGINE_1.1.15\web\CController.php(286): CartController->runAction()
#2 D:\Website\YII_ENGINE_1.1.15\web\CController.php(265): CartController->runActionWithFilters()
#3 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CartController->run()
#4 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\Website\YIIMOLTINCART\index.php(11): CWebApplication->run()
REQUEST_URI=/cart/insert
2014/07/31 22:20:50 [error] [php] Argument 2 passed to Moltin\Cart\Cart::__construct() must be an instance of Moltin\Cart\IdentifierInterface, none given, called in D:\Website\YIIMOLTINCART\protected\controllers\CartController.php on line 60 and defined (D:\Website\YIIMOLTINCART\protected\vendors\MoltinCart\src\Moltin\Cart\Cart.php:48)
Stack trace:
#0 D:\Website\YII_ENGINE_1.1.15\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\Website\YII_ENGINE_1.1.15\web\CController.php(286): CartController->runAction()
#2 D:\Website\YII_ENGINE_1.1.15\web\CController.php(265): CartController->runActionWithFilters()
#3 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(282): CartController->run()
#4 D:\Website\YII_ENGINE_1.1.15\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\Website\YII_ENGINE_1.1.15\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\Website\YIIMOLTINCART\index.php(11): CWebApplication->run()
REQUEST_URI=/cart/read
